// lib/rulebookIndexData.ts

export const RULEBOOK_INDEX = [
    { title: "Rolagem de Dados", page: 4 },
    { title: "Regras de Críticos", page: 5 },
    { title: "Atributos", page: 6 },
    { title: "Tipos de Ação", page: 7 },
    { title: "Tipos de Danos", page: 8 },
    { title: "Tipos de Status", page: 9 },
    { title: "Manobras de Combate", page: 10 },
    { title: "Momentum", page: 11 },
    { title: "Mundo e Economia", page: 12 },
    { title: "Arsenal dos Caçadores", page: 13 },
    { title: "Lista de Venenos", page: 14 },
    { title: "Criando seu Personagem", page: 15 },
    { title: "Origens", page: 16 },
    { title: "Habilidades", page: 17 },
    { title: "Classes de Caçadores", page: 18 },
    { title: "Estilos de Luta", page: 19 },
    { title: "Ranks e Recompensas", page: 20 },
    { title: "Progressão de Nível", page: 21 },
    { title: "Marca do Caçador", page: 22 },
    { title: "Mundo Transparente", page: 23 },
    { title: "Estado Altruísta", page: 24 },
    { title: "Lâmina Carmesim", page: 25 },
    { title: "Momento da Conexão", page: 26 },
    { title: "Criando sua Respiração", page: 27 },
    { title: "Companheiro Oni", page: 28 },
    { title: "Linhagem das Respirações", page: 29 },
    { title: "Respiração da Água", page: 30 },
    { title: "Respiração das Chamas", page: 31 },
    { title: "Respiração do Vento", page: 32 },
    { title: "Respiração da Pedra", page: 33 },
    { title: "Respiração do Trovão", page: 34 },
    { title: "Respiração da Flor", page: 35 },
    { title: "Respiração do Inseto", page: 36 },
    { title: "Respiração da Serpente", page: 37 },
    { title: "Respiração da Névoa", page: 38 },
    { title: "Respiração da Besta", page: 39 },
    { title: "Respiração do Som", page: 40 },
    { title: "Respiração do Amor", page: 41 },
    { title: "Respiração do Sol", page: 42 },
    { title: "Respiração da Lua", page: 43 },
    { title: "Origens Onis", page: 44 },
    { title: "Classes Onis", page: 45 },
    { title: "Habilidades Onis", page: 46 },
    { title: "Progressão de Níveis de Onis", page: 47 },
    { title: "Regras de Criação de Kekkijutsu", page: 48 },
    { title: "Fichas Prontas de Caçadores", page: 49 },
];